apiVersion: apps/v1
kind: Deployment
metadata:
  name: minionz-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: minionz-backend
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: minionz-backend
    spec:
      containers:
        - name: container
          image: minionz/backend:latest
      terminationGracePeriodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    type: minionz-backend
  ports:
    - port: 8080
      name: "svc8080"
      targetPort: 8080