apiVersion: apps/v1
kind: Deployment
metadata:
  name: minionz-backend-new
spec:
  replicas: 2
  selector:
    matchLabels:
      type: minionz-backend-new
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: minionz-backend-new
    spec:
      containers:
        - name: container
          image: minionz/backend:latest
          readinessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
      terminationGracePeriodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: canary-backend-new
spec:
  selector:
    type: minionz-backend-new
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-new
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: canary-backend-new
                port:
                  number: 8080