apiVersion: apps/v1
kind: Deployment
metadata:
  name: minionz-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minionz-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minionz-frontend
    spec:
      containers:
        - name: minionz-frontend
          image: minionz/frontend:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: minionz-frontend
  ports:
    - port: 80
      name: "svc80"
      targetPort: 80
  type: LoadBalancer